apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: teamtwohotel
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 690521455231.dkr.ecr.ap-northeast-2.amazonaws.com/admin-order:latest
          ports:
            - containerPort: 8080
